// Command generate-theme-doc ports scripts/generate-theme-doc.js: it reads
// the theme names via internal/themes and regenerates themes/README.md
// with the same template. Run from the repository root:
//
//	go run ./scripts/go/generate-theme-doc
package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/wthrajat/github-readme-stats/internal/themes"
)

const targetFile = "themes/README.md"

// themeNames returns the sorted theme names from internal/themes,
// ported from themes/index.js. Sorting keeps the generated output
// deterministic across runs (Go map order is random).
func themeNames() []string {
	names := make([]string, 0, len(themes.Themes))
	for name := range themes.Themes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func createRepoMdLink(theme string) string {
	return fmt.Sprintf("\n[%s_repo]: https://rajat-grs.vercel.app/api/pin/?username=wthrajat&repo=github-readme-stats&cache_seconds=86400&theme=%s", theme, theme)
}

func createStatMdLink(theme string) string {
	return fmt.Sprintf("\n[%s]: https://rajat-grs.vercel.app/api?username=wthrajat&show_icons=true&hide=contribs,prs&cache_seconds=86400&theme=%s", theme, theme)
}

func generateLinks(names []string, fn func(string) string) string {
	var b strings.Builder
	for _, name := range names {
		b.WriteString(fn(name))
	}
	return b.String()
}

func createTableItem(link, label string, isRepoCard bool) string {
	if link == "" || label == "" {
		return ""
	}
	suffix := ""
	if isRepoCard {
		suffix = "_repo"
	}
	return fmt.Sprintf("`%s` ![%s][%s%s]", label, link, link, suffix)
}

func generateTable(names []string, isRepoCard bool) string {
	excluded := "default_repocard"
	if isRepoCard {
		excluded = "default"
	}
	var filtered []string
	for _, name := range names {
		if name != excluded {
			filtered = append(filtered, name)
		}
	}

	var rows []string
	for i := 0; i < len(filtered); i += 3 {
		var one, two, three string
		one = filtered[i]
		if i+1 < len(filtered) {
			two = filtered[i+1]
		}
		if i+2 < len(filtered) {
			three = filtered[i+2]
		}

		item1 := createTableItem(one, one, isRepoCard)
		item2 := createTableItem(two, two, isRepoCard)
		item3 := createTableItem(three, three, isRepoCard)
		if three == "" {
			item3 = "[Add your theme][add-theme]"
		}
		rows = append(rows, fmt.Sprintf("| %s | %s | %s |", item1, item2, item3))

		// If it's the last row and the row has no empty space, push a new row.
		if three != "" && i+3 == len(filtered) {
			rows = append(rows, "| [Add your theme][add-theme] | | |")
		}
	}
	return strings.Join(rows, "\n")
}

const template = `## Available Themes

<!-- DO NOT EDIT THIS FILE DIRECTLY -->

With inbuilt themes, you can customize the look of the card without doing any manual customization.

Use ` + "`?theme=THEME_NAME`" + ` parameter like so:

` + "```md" + `
![Rajat's GitHub stats](https://rajat-grs.vercel.app/api?username=wthrajat&theme=dark&show_icons=true)
` + "```" + `

## Stats

> These themes works with all five our cards: Stats Card, Repo Card, Gist Card, Top languages Card and WakaTime Card.

| | | |
| :--: | :--: | :--: |
<!-- STATS_CARD_TABLE -->

## Repo Card

> These themes works with all five our cards: Stats Card, Repo Card, Gist Card, Top languages Card and WakaTime Card.

| | | |
| :--: | :--: | :--: |
<!-- REPO_CARD_TABLE -->

<!-- STATS_CARD_LINKS -->

<!-- REPO_CARD_LINKS -->


[add-theme]: https://github.com/wthrajat/github-readme-stats/edit/main/internal/themes/themes.go

Want to add a new theme? Consider reading the [contribution guidelines](../CONTRIBUTING.md#themes-contribution) :D
`

func buildReadme(names []string) string {
	out := template
	out = strings.ReplaceAll(out, "<!-- REPO_CARD_LINKS -->", generateLinks(names, createRepoMdLink))
	out = strings.ReplaceAll(out, "<!-- STATS_CARD_LINKS -->", generateLinks(names, createStatMdLink))
	out = strings.ReplaceAll(out, "<!-- REPO_CARD_TABLE -->", generateTable(names, true))
	out = strings.ReplaceAll(out, "<!-- STATS_CARD_TABLE -->", generateTable(names, false))
	return out
}

func main() {
	names := themeNames()
	if len(names) == 0 {
		log.Fatal("no themes found in internal/themes")
	}
	if err := os.WriteFile(targetFile, []byte(buildReadme(names)), 0644); err != nil {
		log.Fatalf("write %s: %v", targetFile, err)
	}
	log.Printf("wrote %s with %d themes", targetFile, len(names))
}
